services:
  api:
    build: ./apps/api
    image: api
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  worker:
    build: ./apps/worker
    image: worker
    env_file:
      - .env
    depends_on:
      - redis
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/
  redis:
    image: redis:7
    ports:
      - 6379:6379 
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    #volumes:
    #  - redis-data:/data

volumes:
  pg-data:
  #redis-data: